title: sebanalysis
email: sebanalysis@protonmail.com
description: >-
  A place to learn about the taxonomy of things.
twitter_username: sebanalysis
github_username: sebanalysis
remote_theme:  rahul-bothra/parchment
plugins:
  - jekyll-include-cache
